# Generated by Django 3.2.10 on 2022-01-03 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateField(default=datetime.date.today)),
                ('entry', models.CharField(blank=True, max_length=30)),
                ('numbers', models.IntegerField(blank=True)),
                ('owner', models.CharField(max_length=330)),
            ],
            options={
                'ordering': ['tdate'],
            },
        ),
    ]
