# Generated by Django 3.2.10 on 2022-01-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrymodel',
            options={},
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='entry_body',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='owner',
            field=models.CharField(blank=True, max_length=330),
        ),
    ]
