# Generated by Django 3.2.10 on 2022-01-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0002_auto_20220104_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='entry_body',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
    ]
