# Generated by Django 3.2.10 on 2022-01-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0003_alter_entrymodel_entry_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='entry_body',
            field=models.CharField(default='detail', max_length=3000),
        ),
    ]
