# Generated by Django 3.2.10 on 2022-01-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0004_alter_entrymodel_entry_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrymodel',
            old_name='numbers',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='entrymodel',
            old_name='tdate',
            new_name='date',
        ),
    ]
