# Generated by Django 3.2.10 on 2022-01-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0005_auto_20220109_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='pre_delete',
            field=models.BooleanField(default=False),
        ),
    ]
